/**
 * Generate `assets/fonts.generated.css` based on which FK Grotesk OTF files
 * actually exist in `public/fonts/`.
 *
 * Why: FK Grotesk is a commercial font; the .otf files are gitignored.
 * If we ship a hand-written fonts.css that references files that aren't
 * deployed, the browser fetches `/fonts/FKGrotesk-Regular.otf`, the SPA
 * fall-through returns the index HTML, and the browser logs
 *   "OTS parsing error: invalid sfntVersion: 1008813135"
 * (1008813135 == ASCII "<!DO"). This script only emits @font-face rules
 * for files that exist at build time, so production silently falls back
 * to the system stack instead of decoding HTML as fonts.
 *
 * Runs as `predev` and `prebuild` hooks in package.json.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

interface FaceSpec {
    family: 'FK Grotesk' | 'FK Grotesk Mono';
    file: string;
    weight: number;
    style: 'normal' | 'italic';
}

const SPECS: FaceSpec[] = [
    { family: 'FK Grotesk', file: 'FKGrotesk-Thin.otf', weight: 100, style: 'normal' },
    { family: 'FK Grotesk', file: 'FKGrotesk-ThinItalic.otf', weight: 100, style: 'italic' },
    { family: 'FK Grotesk', file: 'FKGrotesk-Light.otf', weight: 300, style: 'normal' },
    { family: 'FK Grotesk', file: 'FKGrotesk-LightItalic.otf', weight: 300, style: 'italic' },
    { family: 'FK Grotesk', file: 'FKGrotesk-Regular.otf', weight: 400, style: 'normal' },
    { family: 'FK Grotesk', file: 'FKGrotesk-Italic.otf', weight: 400, style: 'italic' },
    { family: 'FK Grotesk', file: 'FKGrotesk-Medium.otf', weight: 500, style: 'normal' },
    { family: 'FK Grotesk', file: 'FKGrotesk-MediumItalic.otf', weight: 500, style: 'italic' },
    { family: 'FK Grotesk', file: 'FKGrotesk-Bold.otf', weight: 700, style: 'normal' },
    { family: 'FK Grotesk', file: 'FKGrotesk-BoldItalic.otf', weight: 700, style: 'italic' },
    { family: 'FK Grotesk', file: 'FKGrotesk-Black.otf', weight: 900, style: 'normal' },
    { family: 'FK Grotesk', file: 'FKGrotesk-BlackItalic.otf', weight: 900, style: 'italic' },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Thin.otf', weight: 100, style: 'normal' },
    {
        family: 'FK Grotesk Mono',
        file: 'FKGroteskMono-ThinItalic.otf',
        weight: 100,
        style: 'italic',
    },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Light.otf', weight: 300, style: 'normal' },
    {
        family: 'FK Grotesk Mono',
        file: 'FKGroteskMono-LightItalic.otf',
        weight: 300,
        style: 'italic',
    },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Regular.otf', weight: 400, style: 'normal' },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Italic.otf', weight: 400, style: 'italic' },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Medium.otf', weight: 500, style: 'normal' },
    {
        family: 'FK Grotesk Mono',
        file: 'FKGroteskMono-MediumItalic.otf',
        weight: 500,
        style: 'italic',
    },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Bold.otf', weight: 700, style: 'normal' },
    {
        family: 'FK Grotesk Mono',
        file: 'FKGroteskMono-BoldItalic.otf',
        weight: 700,
        style: 'italic',
    },
    { family: 'FK Grotesk Mono', file: 'FKGroteskMono-Black.otf', weight: 900, style: 'normal' },
    {
        family: 'FK Grotesk Mono',
        file: 'FKGroteskMono-BlackItalic.otf',
        weight: 900,
        style: 'italic',
    },
];

function emitFace(spec: FaceSpec): string {
    return [
        '@font-face {',
        `    font-family: '${spec.family}';`,
        `    src: url('/fonts/${spec.file}') format('opentype');`,
        `    font-weight: ${spec.weight};`,
        `    font-style: ${spec.style};`,
        '    font-display: swap;',
        '}',
    ].join('\n');
}

function main(): void {
    const fontsDir = path.resolve('public/fonts');
    const outPath = path.resolve('assets/fonts.generated.css');

    const present = SPECS.filter((s) => fs.existsSync(path.join(fontsDir, s.file)));
    const missing = SPECS.filter((s) => !fs.existsSync(path.join(fontsDir, s.file)));

    const banner = [
        '/*',
        ' * AUTO-GENERATED by scripts/build-fonts-css.ts. Do not edit by hand.',
        ' * Emits @font-face rules only for files that exist in public/fonts/.',
        ` * ${present.length}/${SPECS.length} faces resolved at build time.`,
        ' */',
        '',
    ].join('\n');

    const body =
        present.length === 0
            ? '/* No FK Grotesk OTF files found. Falling back to system stack. */\n'
            : present.map(emitFace).join('\n\n') + '\n';

    fs.writeFileSync(outPath, banner + '\n' + body, 'utf-8');

    if (present.length === SPECS.length) {
        console.log(`[fonts] Wrote ${outPath} with all ${SPECS.length} FK Grotesk faces.`);
    } else {
        console.log(
            `[fonts] Wrote ${outPath} with ${present.length}/${SPECS.length} faces. Missing: ${missing.map((m) => m.file).join(', ') || 'none'}`
        );
    }
}

main();
